---
client:
    name: FiveTwo
    password_encoder: bcrypt
    session_expire: 120
database:
    host: localhost
    port:
    database: ilias
    engine: innodb
    encoding: utf8_unicode_ci
    create_db: 1
language:
    default: en
    available: 
        - en
server:
    http_path: https://localhost/ILIAS
    timezone: Europe/Berlin
setup:
    master_password: abcdef
tools:
    convert: /usr/bin/convert
    zip: /bin/zip
    unzip: /bin/unzip
    java: /usr/bin/java
log:
    file_name: ilias.log
git:
    url: https://github.com/ILIAS-eLearning/ILIAS.git
    branch: release_5-2
 https_auto_detect:
    enabled: 0
    header_name: X-FORWARDED-SCHEME
    header_value: https
